import type { ProviderConfig, ProviderId } from './types.js'

const reasoningOptions = [
  { label: '低', value: 'low' },
  { label: '中', value: 'medium' },
  { label: '高', value: 'high' },
] as const

export const PROVIDER_REGISTRY: Record<ProviderId, ProviderConfig> = {
  // ---------------------------------------------------------
  // 第一梯队：已完整接入的 Native / 预设 Provider
  // ---------------------------------------------------------
  anthropic: {
    id: 'anthropic',
    label: 'Anthropic',
    description: 'Claude 原生入口，适合工具调用、多模态和高质量推理。',
    recommendedFor: 'Claude 原生体验、复杂工具调用、多模态工作流',
    adapterKind: 'anthropic-native',
    baseUrl: 'https://api.anthropic.com',
    baseUrlEditable: true,
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    apiKeyLabel: 'Anthropic API Key',
    apiKeyPlaceholder: 'sk-ant-...',
    docsUrl: 'https://console.anthropic.com/',
    defaultModel: 'claude-sonnet-4-6',
    models: ['claude-sonnet-4-6', 'claude-opus-4-1', 'claude-haiku-4-5'],
    modelMetadata: {
      'claude-sonnet-4-6': {
        label: 'Claude Sonnet 4.6',
        description: '均衡的通用编码与代理模型。',
        recommendedFor: '编码、代理执行、工具调用',
        contextWindow: '200K',
        inputPrice: '$3/M',
        outputPrice: '$15/M',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
      'claude-opus-4-1': {
        label: 'Claude Opus 4.1',
        description: '最强推理能力，适合复杂规划。',
        recommendedFor: '高复杂度规划、深度分析、长链推理',
        contextWindow: '200K',
        inputPrice: '$15/M',
        outputPrice: '$75/M',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
      'claude-haiku-4-5': {
        label: 'Claude Haiku 4.5',
        description: '轻量快速，适合低成本场景。',
        recommendedFor: '轻量问答、快速补全、低成本任务',
        contextWindow: '200K',
        inputPrice: '$1/M',
        outputPrice: '$5/M',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    supportsReasoningEffort: true,
  },
  'openai-compatible': {
    id: 'openai-compatible',
    label: 'OpenAI Compatible',
    description: '通用 OpenAI 兼容入口，适合自定义或未知兼容服务。',
    recommendedFor: '兼容 OpenAI /chat/completions 的任意平台',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://api.openai.com/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'OPENAI_API_KEY',
    apiKeyLabel: 'OpenAI Compatible API Key',
    apiKeyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    defaultModel: 'gpt-4o-mini',
    models: ['gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'custom-openai-model'],
    modelMetadata: {
      'gpt-4o-mini': {
        label: 'GPT-4o mini',
        description: '成本较低的通用兼容默认模型。',
        recommendedFor: '通用问答、轻量编码、低成本默认选择',
        contextWindow: '128K',
        inputPrice: '$0.15/M',
        outputPrice: '$0.6/M',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
      'gpt-4.1': {
        label: 'GPT-4.1',
        description: '更强的复杂任务处理能力。',
        recommendedFor: '复杂分析、长上下文处理、严谨工具链任务',
        contextWindow: '1M',
        inputPrice: '$2/M',
        outputPrice: '$8/M',
        reasoningEfforts: ['low', 'medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
      'gpt-4.1-mini': {
        label: 'GPT-4.1 mini',
        description: '更快更便宜的 4.1 系列。',
        recommendedFor: '高频交互、轻量代理、成本控制',
        contextWindow: '1M',
        inputPrice: '$0.4/M',
        outputPrice: '$1.6/M',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: '更高 effort 可以提升深度，但会增加延迟与 token 消耗。',
        options: [...reasoningOptions],
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    description: '聚合平台入口，可统一调用多个上游模型与厂商。',
    recommendedFor: '快速切换多个模型供应商、统一账单与路由',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'OPENROUTER_API_KEY',
    apiKeyLabel: 'OpenRouter API Key',
    apiKeyPlaceholder: 'sk-or-v1-...',
    docsUrl: 'https://openrouter.ai/docs',
    defaultModel: 'openai/gpt-4o-mini',
    models: ['openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet', 'google/gemini-2.0-flash-001'],
    modelMetadata: {
      'openai/gpt-4o-mini': {
        label: 'OpenAI GPT-4o mini',
        description: '低成本通用默认模型。',
        contextWindow: '128K',
        inputPrice: '$0.15/M',
        outputPrice: '$0.6/M',
        reasoningEfforts: ['low', 'medium'],
      },
      'anthropic/claude-3.5-sonnet': {
        label: 'Anthropic Claude 3.5 Sonnet',
        description: 'OpenRouter 上的 Claude 路由选择。',
        contextWindow: '200K',
        inputPrice: '$3/M',
        outputPrice: '$15/M',
        reasoningEfforts: ['medium', 'high'],
      },
      'google/gemini-2.0-flash-001': {
        label: 'Google Gemini 2.0 Flash',
        description: '高吞吐、快速响应。',
        contextWindow: '1M',
        inputPrice: '$0.1/M',
        outputPrice: '$0.4/M',
        reasoningEfforts: ['low', 'medium'],
      },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'siteUrl',
        label: 'Site URL',
        type: 'text',
        placeholder: 'https://your-app.example.com',
        description: '可选，用于 OpenRouter 的 HTTP-Referer 头。',
      },
      {
        key: 'appName',
        label: 'App Name',
        type: 'text',
        placeholder: 'My Agent Workspace',
        description: '可选，用于 OpenRouter 的 X-Title 头。',
      },
    ],
  },
  'azure-openai': {
    id: 'azure-openai',
    label: 'Azure OpenAI',
    description: 'Azure 企业托管入口，适合内网、合规与企业采购场景。',
    recommendedFor: 'Azure 企业环境、私有网络、合规要求较高的接入',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://your-resource.openai.azure.com',
    baseUrlEditable: true,
    baseUrlRequired: true,
    apiKeyEnv: 'AZURE_OPENAI_API_KEY',
    apiKeyLabel: 'Azure OpenAI API Key',
    apiKeyPlaceholder: '请输入 Azure OpenAI Key',
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/',
    defaultModel: 'gpt-4o-mini',
    models: ['gpt-4o-mini', 'gpt-4.1', 'o3-mini'],
    modelMetadata: {
      'gpt-4o-mini': {
        label: 'GPT-4o mini',
        description: 'Azure 上常见的高性价比部署模型。',
        contextWindow: '128K',
        inputPrice: '以 Azure 区域定价为准',
        outputPrice: '以 Azure 区域定价为准',
        reasoningEfforts: ['low', 'medium'],
      },
      'gpt-4.1': {
        label: 'GPT-4.1',
        description: '企业托管的通用强模型。',
        contextWindow: '1M',
        inputPrice: '以 Azure 区域定价为准',
        outputPrice: '以 Azure 区域定价为准',
        reasoningEfforts: ['low', 'medium', 'high'],
      },
      'o3-mini': {
        label: 'o3-mini',
        description: '更偏 reasoning 的经济型模型。',
        contextWindow: '200K',
        inputPrice: '以 Azure 区域定价为准',
        outputPrice: '以 Azure 区域定价为准',
        reasoningEfforts: ['medium', 'high'],
      },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'deployment',
        label: 'Deployment Name',
        type: 'text',
        required: true,
        placeholder: 'my-gpt-4o-mini',
        description: 'Azure OpenAI 的 deployment 名称。',
      },
      {
        key: 'apiVersion',
        label: 'API Version',
        type: 'text',
        placeholder: '2024-10-21',
        description: 'Azure OpenAI API 版本，可留空使用默认值。',
      },
    ],
  },
  groq: {
    id: 'groq',
    label: 'Groq',
    description: '高吞吐低延迟推理入口，适合速度敏感场景。',
    recommendedFor: '低延迟交互、快速生成、工具链加速',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'GROQ_API_KEY',
    apiKeyLabel: 'Groq API Key',
    apiKeyPlaceholder: 'gsk_...',
    docsUrl: 'https://console.groq.com/docs',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    modelMetadata: {
      'llama-3.3-70b-versatile': {
        label: 'Llama 3.3 70B Versatile',
        description: 'Groq 上常用的强能力默认模型。',
        contextWindow: '128K',
      },
      'llama-3.1-8b-instant': {
        label: 'Llama 3.1 8B Instant',
        description: '极快响应，适合轻量任务。',
        contextWindow: '128K',
      },
      'mixtral-8x7b-32768': {
        label: 'Mixtral 8x7B',
        description: '常见的低延迟开源模型选择。',
        contextWindow: '32K',
      },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    isOpenAICompatiblePreset: true,
  },
  ollama: {
    id: 'ollama',
    label: 'Ollama',
    description: '本地 Ollama 服务入口，适合离线与本地开发。',
    recommendedFor: '本地模型、快速实验、低门槛部署',
    adapterKind: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:11434/v1',
    baseUrlEditable: true,
    baseUrlRequired: true,
    apiKeyLabel: 'Ollama API Key（可留空）',
    apiKeyPlaceholder: '多数本地服务无需填写',
    defaultModel: 'qwen2.5-coder:7b',
    models: ['qwen2.5-coder:7b', 'deepseek-r1:8b', 'llama3.2:3b'],
    modelMetadata: {
      'qwen2.5-coder:7b': {
        label: 'Qwen2.5 Coder 7B',
        description: '适合本地编码与脚本任务。',
        contextWindow: '32K',
      },
      'deepseek-r1:8b': {
        label: 'DeepSeek R1 8B',
        description: '本地 reasoning 实验模型。',
        contextWindow: '32K',
        reasoningEfforts: ['low', 'medium'],
      },
      'llama3.2:3b': {
        label: 'Llama 3.2 3B',
        description: '轻量快速本地模型。',
        contextWindow: '8K',
      },
    },
    capabilities: { streaming: true, tools: false, vision: false, reasoning: true },
    local: true,
    isOpenAICompatiblePreset: true,
  },
  deepseek: {
    id: 'deepseek',
    label: 'DeepSeek',
    description: 'DeepSeek 官方 API，适合编码和 reasoning 任务。',
    recommendedFor: '中文编码、推理与成本敏感任务',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    apiKeyLabel: 'DeepSeek API Key',
    apiKeyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.deepseek.com/',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    modelMetadata: {
      'deepseek-chat': {
        label: 'DeepSeek Chat',
        description: '通用对话与编码。',
        contextWindow: '64K',
        inputPrice: '以官方定价为准',
        outputPrice: '以官方定价为准',
        reasoningEfforts: ['low', 'medium'],
      },
      'deepseek-reasoner': {
        label: 'DeepSeek Reasoner',
        description: '更偏推理与思考链任务。',
        contextWindow: '64K',
        inputPrice: '以官方定价为准',
        outputPrice: '以官方定价为准',
        reasoningEfforts: ['medium', 'high'],
      },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
  },
  kimi: {
    id: 'kimi',
    label: 'Kimi',
    description: 'Moonshot/Kimi 官方 API，适合长上下文中文任务。',
    recommendedFor: '长上下文、中文知识整理',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://api.moonshot.cn/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'KIMI_API_KEY',
    apiKeyLabel: 'Kimi API Key',
    apiKeyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.moonshot.cn/',
    defaultModel: 'moonshot-v1-8k',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    modelMetadata: {
      'moonshot-v1-8k': { label: 'Moonshot 8K', description: '轻量上下文版本。', contextWindow: '8K' },
      'moonshot-v1-32k': { label: 'Moonshot 32K', description: '中等长上下文。', contextWindow: '32K' },
      'moonshot-v1-128k': { label: 'Moonshot 128K', description: '长上下文处理。', contextWindow: '128K' },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    isOpenAICompatiblePreset: true,
  },
  minimax: {
    id: 'minimax',
    label: 'MiniMax',
    description: 'MiniMax 官方入口，适合中文场景与多样化模型路线。',
    recommendedFor: '国内业务场景、中文内容生成',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://api.minimax.chat/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'MINIMAX_API_KEY',
    apiKeyLabel: 'MiniMax API Key',
    apiKeyPlaceholder: '请输入 MiniMax Key',
    docsUrl: 'https://www.minimaxi.com/platform',
    defaultModel: 'MiniMax-Text-01',
    models: ['MiniMax-Text-01', 'MiniMax-M1'],
    modelMetadata: {
      'MiniMax-Text-01': { label: 'MiniMax Text 01', description: '通用文本模型。' },
      'MiniMax-M1': { label: 'MiniMax M1', description: '更强能力版本。', reasoningEfforts: ['medium', 'high'] },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    isOpenAICompatiblePreset: true,
  },
  lmstudio: {
    id: 'lmstudio',
    label: 'LM Studio',
    description: 'LM Studio 本地桌面模型入口，适合本机调试与可视化管理。',
    recommendedFor: '桌面本地模型、开发调试、离线实验',
    adapterKind: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:1234/v1',
    baseUrlEditable: true,
    baseUrlRequired: true,
    apiKeyLabel: 'LM Studio API Key（可留空）',
    apiKeyPlaceholder: '多数本地服务无需填写',
    docsUrl: 'https://lmstudio.ai/docs',
    defaultModel: 'local-model',
    models: ['local-model', 'qwen2.5-7b-instruct', 'llama-3.1-8b-instruct'],
    modelMetadata: {
      'local-model': { label: 'Local Model', description: 'LM Studio 当前默认本地模型。' },
      'qwen2.5-7b-instruct': { label: 'Qwen2.5 7B Instruct', description: '本地通用指令模型。', contextWindow: '32K' },
      'llama-3.1-8b-instruct': { label: 'Llama 3.1 8B Instruct', description: '常用本地推理模型。', contextWindow: '32K' },
    },
    capabilities: { streaming: true, tools: false, vision: false, reasoning: true },
    local: true,
    isOpenAICompatiblePreset: true,
  },
  localai: {
    id: 'localai',
    label: 'LocalAI',
    description: '本地/自托管 OpenAI 兼容服务入口，适合私有部署。',
    recommendedFor: '私有部署、服务器自托管、内网模型网关',
    adapterKind: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:8080/v1',
    baseUrlEditable: true,
    baseUrlRequired: true,
    apiKeyEnv: 'LOCALAI_API_KEY',
    apiKeyLabel: 'LocalAI API Key（可留空）',
    apiKeyPlaceholder: '按你的 LocalAI 配置决定，可为空',
    docsUrl: 'https://localai.io/',
    defaultModel: 'gpt-4all-j',
    models: ['gpt-4all-j', 'mistral-7b-instruct', 'llama-3.1-8b-instruct'],
    modelMetadata: {
      'gpt-4all-j': { label: 'GPT4All J', description: '经典本地部署默认模型。' },
      'mistral-7b-instruct': { label: 'Mistral 7B Instruct', description: '通用本地指令模型。', contextWindow: '8K' },
      'llama-3.1-8b-instruct': { label: 'Llama 3.1 8B Instruct', description: '常见本地部署选择。', contextWindow: '32K' },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    local: true,
    isOpenAICompatiblePreset: true,
  },
  // ---------------------------------------------------------
  // 第二梯队：仅留扩展位，待后续完整集成的 Provider
  // ---------------------------------------------------------
  gemini: {
    id: 'gemini',
    label: 'Google Gemini',
    description: 'Google Gemini 入口，适合长上下文、多模态与高吞吐任务。',
    recommendedFor: '长上下文、多模态、快速推理与通用问答',
    group: 'cloud',
    maturity: 'beta',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    baseUrlEditable: true,
    apiKeyEnv: 'GEMINI_API_KEY',
    apiKeyLabel: 'Gemini API Key',
    apiKeyPlaceholder: 'AIza...',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/openai',
    defaultModel: 'gemini-2.0-flash',
    models: ['gemini-2.0-flash', 'gemini-2.5-pro-preview-03-25'],
    modelMetadata: {
      'gemini-2.0-flash': {
        label: 'Gemini 2.0 Flash',
        description: '高吞吐、低延迟的通用主力模型。',
        recommendedFor: '快速交互、轻量代理、多模态输入',
        contextWindow: '1M',
        inputPrice: '以 Google 官方定价为准',
        outputPrice: '以 Google 官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
      'gemini-2.5-pro-preview-03-25': {
        label: 'Gemini 2.5 Pro Preview',
        description: '更强的复杂推理与规划能力。',
        recommendedFor: '复杂分析、长链推理、方案设计',
        contextWindow: '1M',
        inputPrice: '以 Google 官方定价为准',
        outputPrice: '以 Google 官方定价为准',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: 'Gemini 的推理深度控制（通过统一产品语义映射）。',
        options: [...reasoningOptions],
      },
    ],
  },
  bedrock: {
    id: 'bedrock',
    label: 'AWS Bedrock',
    description: 'AWS 企业托管入口。（预留位，后续版本接入）',
    maturity: 'planned',
    adapterKind: 'anthropic-native', // Bedrock Anthropic typically shares native SDK shape
    defaultModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    models: ['anthropic.claude-3-5-sonnet-20241022-v2:0', 'anthropic.claude-3-haiku-20240307-v1:0'],
    capabilities: { streaming: true, tools: true, vision: true },
  },
  vertex: {
    id: 'vertex',
    label: 'GCP Vertex AI',
    description: 'Google Cloud 企业托管入口。（预留位，后续版本接入）',
    maturity: 'planned',
    adapterKind: 'anthropic-native',
    defaultModel: 'claude-3-5-sonnet@20240620',
    models: ['claude-3-5-sonnet@20240620', 'claude-3-haiku@20240307'],
    capabilities: { streaming: true, tools: true, vision: true },
  },
  zhipu: {
    id: 'zhipu',
    label: '智谱 Zhipu',
    description: '智谱 AI 大模型开放平台，适合中文问答、通用推理与多模态扩展。',
    recommendedFor: '中文通用对话、知识问答、国内业务接入',
    group: 'cloud',
    maturity: 'beta',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    baseUrlEditable: true,
    apiKeyEnv: 'ZHIPU_API_KEY',
    apiKeyLabel: 'Zhipu API Key',
    apiKeyPlaceholder: '请输入智谱 API Key',
    docsUrl: 'https://open.bigmodel.cn/',
    defaultModel: 'glm-4-plus',
    models: ['glm-4-plus', 'glm-4-flash', 'glm-4-air'],
    modelMetadata: {
      'glm-4-plus': {
        label: 'GLM-4 Plus',
        description: '智谱的高能力通用模型。',
        recommendedFor: '中文推理、知识任务、综合问答',
        contextWindow: '128K',
        inputPrice: '以智谱官方定价为准',
        outputPrice: '以智谱官方定价为准',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
      'glm-4-flash': {
        label: 'GLM-4 Flash',
        description: '更快更便宜的通用模型。',
        recommendedFor: '高频交互、轻量任务、成本敏感场景',
        contextWindow: '128K',
        inputPrice: '以智谱官方定价为准',
        outputPrice: '以智谱官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
      'glm-4-air': {
        label: 'GLM-4 Air',
        description: '更轻量的通用入口。',
        recommendedFor: '轻量聊天、默认低成本接入',
        contextWindow: '128K',
        inputPrice: '以智谱官方定价为准',
        outputPrice: '以智谱官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: '智谱模型支持时可通过统一产品语义控制推理深度。',
        options: [...reasoningOptions],
      },
    ],
  },
  dashscope: {
    id: 'dashscope',
    label: '阿里百炼 DashScope',
    description: '阿里云百炼 / 通义 Qwen 生态入口，适合中文和企业业务场景。',
    recommendedFor: 'Qwen 系列、中文业务、企业接入',
    group: 'cloud',
    maturity: 'beta',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    baseUrlEditable: true,
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    apiKeyLabel: 'DashScope API Key',
    apiKeyPlaceholder: '请输入百炼 API Key',
    docsUrl: 'https://bailian.console.aliyun.com/',
    defaultModel: 'qwen-max',
    models: ['qwen-max', 'qwen-plus', 'qwen-turbo'],
    modelMetadata: {
      'qwen-max': {
        label: 'Qwen Max',
        description: '通义的高能力通用模型。',
        recommendedFor: '复杂推理、中文写作、综合问答',
        contextWindow: '128K',
        inputPrice: '以阿里百炼官方定价为准',
        outputPrice: '以阿里百炼官方定价为准',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
      'qwen-plus': {
        label: 'Qwen Plus',
        description: '均衡的通用模型。',
        recommendedFor: '默认通用接入、性价比平衡',
        contextWindow: '128K',
        inputPrice: '以阿里百炼官方定价为准',
        outputPrice: '以阿里百炼官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
      'qwen-turbo': {
        label: 'Qwen Turbo',
        description: '更快更轻量的 Qwen 模型。',
        recommendedFor: '高频交互、轻量问答、低成本任务',
        contextWindow: '128K',
        inputPrice: '以阿里百炼官方定价为准',
        outputPrice: '以阿里百炼官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: '通义/Qwen 模型支持时可通过统一产品语义控制推理深度。',
        options: [...reasoningOptions],
      },
    ],
  },
  doubao: {
    id: 'doubao',
    label: '字节豆包 Doubao',
    description: '火山引擎豆包大模型入口，适合中文内容生成与通用业务场景。',
    recommendedFor: '中文内容生成、国内业务、字节生态',
    group: 'cloud',
    maturity: 'beta',
    adapterKind: 'openai-compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    baseUrlEditable: true,
    apiKeyEnv: 'DOUBAO_API_KEY',
    apiKeyLabel: 'Doubao API Key',
    apiKeyPlaceholder: '请输入火山引擎 API Key',
    docsUrl: 'https://www.volcengine.com/product/ark',
    defaultModel: 'doubao-pro-32k',
    models: ['doubao-pro-32k', 'doubao-lite-32k'],
    modelMetadata: {
      'doubao-pro-32k': {
        label: 'Doubao Pro 32K',
        description: '豆包的高能力通用模型。',
        recommendedFor: '中文写作、综合问答、业务对话',
        contextWindow: '32K',
        inputPrice: '以火山引擎官方定价为准',
        outputPrice: '以火山引擎官方定价为准',
        reasoningEfforts: ['medium', 'high'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
      'doubao-lite-32k': {
        label: 'Doubao Lite 32K',
        description: '更快更轻量的豆包模型。',
        recommendedFor: '轻量问答、默认业务接入、成本控制',
        contextWindow: '32K',
        inputPrice: '以火山引擎官方定价为准',
        outputPrice: '以火山引擎官方定价为准',
        reasoningEfforts: ['low', 'medium'],
        capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
      },
    },
    capabilities: { streaming: true, tools: true, vision: false, reasoning: true },
    supportsReasoningEffort: true,
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: '豆包模型支持时可通过统一产品语义控制推理深度。',
        options: [...reasoningOptions],
      },
    ],
  },

  // ---------------------------------------------------------
  // 自定义兜底入口
  // ---------------------------------------------------------
  custom: {
    id: 'custom',
    label: 'Custom',
    description: '完全自定义的兼容入口，适合内部网关或未知兼容服务。',
    recommendedFor: '内部代理、自建网关、实验性 OpenAI 兼容服务',
    adapterKind: 'openai-compatible',
    baseUrlEditable: true,
    baseUrlRequired: true,
    apiKeyLabel: 'Custom API Key',
    apiKeyPlaceholder: '请输入自定义服务 API Key',
    defaultModel: 'custom-model',
    models: ['custom-model'],
    modelMetadata: {
      'custom-model': { label: 'Custom Model', description: '请根据你的兼容服务自行配置。' },
    },
    capabilities: { streaming: true, tools: true, vision: true, reasoning: true },
    isOpenAICompatiblePreset: true,
    settingsSchema: [
      {
        key: 'reasoningEffort',
        label: 'Reasoning Effort',
        type: 'select',
        description: '仅在你的自定义网关支持时生效。',
        options: [...reasoningOptions],
      },
    ],
  },
}

export function listProviders(): ProviderConfig[] {
  return Object.values(PROVIDER_REGISTRY)
}
