export type Message = any;
export type AssistantMessage = any;
export type UserMessage = any;
export type AttachmentMessage = any;
export type SystemMessage = any;
export type SystemLocalCommandMessage = any;
export type ProgressMessage<T = any> = any;
export type ToolUseSummaryMessage = any;
export type TombstoneMessage = any;
export type RequestStartEvent = any;
export type StreamEvent = any;
